### ISSUE TITLE
Prevent auto create topic

### ISSUE THREAD

**Issue by gitSambhal** [algoan/pubsub#507]
Hi @ccoeurderoy 
Is there any option to prevent auto creation of topic and subscription if the new name is given?

**Comment by gitSambhal** [comment]
Hi @g-ongenae @ccoeurderoy 
The above option just preventing the topic auto creation, I also want to prevent the creation of subscription if it doesn't exists in the topic. the `GetSubscriptionOptions` `autoCreate` doesn't seems to work.

**Comment by gitSambhal** [comment]
@ccoeurderoy pls review the [PR ](https://github.com/algoan/pubsub/pull/570)

**Comment by g-ongenae** [comment]
Fixed in #570

**Comment by gitSambhal** [comment]
thanks @g-ongenae
