### ISSUE TITLE
Request: Subscription character separator

### ISSUE THREAD

**Issue by mts88** [algoan/pubsub#78]
Hello, 
thank you for this library, it's amazing, is possible to configure subscription character separator, instead using % as fixed char?

Thank you in advance.

**Comment by ccoeurderoy** [comment]
Hello @mts88, thank you for your feedback 😄 Yes it could be possible, feel free to open a pull request to suggest your feature! Anyway, we'll plan this as soon as possible

**Comment by ccoeurderoy** [comment]
Solved in #80
